//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlaUInspect.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlaUInspect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FindWindow.
        /// </summary>
        public static string FindWindow {
            get {
                return ResourceManager.GetString("FindWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WindowedOnly.
        /// </summary>
        public static string WindowedOnly {
            get {
                return ResourceManager.GetString("WindowedOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DoubleClickToOpen.
        /// </summary>
        public static string DoubleClickToOpen {
            get {
                return ResourceManager.GetString("DoubleClickToOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ControlWalker.
        /// </summary>
        public static string ControlWalker {
            get {
                return ResourceManager.GetString("ControlWalker", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ControlWalkerToolTip.
        /// </summary>
        public static string ControlWalkerToolTip {
            get {
                return ResourceManager.GetString("ControlWalkerToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HighLightSelection.
        /// </summary>
        public static string HighLightSelection {
            get {
                return ResourceManager.GetString("HighLightSelection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HoverMode.
        /// </summary>
        public static string HoverMode {
            get {
                return ResourceManager.GetString("HoverMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FocusTracking.
        /// </summary>
        public static string FocusTracking {
            get {
                return ResourceManager.GetString("FocusTracking", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SaveState.
        /// </summary>
        public static string SaveState {
            get {
                return ResourceManager.GetString("SaveState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to XPathToolTip.
        /// </summary>
        public static string XPathToolTip {
            get {
                return ResourceManager.GetString("XPathToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        public static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SelectItemInTree.
        /// </summary>
        public static string SelectItemInTree {
            get {
                return ResourceManager.GetString("SelectItemInTree", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to XPath.
        /// </summary>
        public static string XPath {
            get {
                return ResourceManager.GetString("XPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PickOverlay.
        /// </summary>
        public static string PickOverlay {
            get {
                return ResourceManager.GetString("PickOverlay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HoverOverlay.
        /// </summary>
        public static string HoverOverlay {
            get {
                return ResourceManager.GetString("HoverOverlay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SelectionOverlay.
        /// </summary>
        public static string SelectionOverlay {
            get {
                return ResourceManager.GetString("SelectionOverlay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AppDescription.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CopyStateToolTip.
        /// </summary>
        public static string CopyStateToolTip {
            get {
                return ResourceManager.GetString("CopyStateToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CopyDetailsToolTip.
        /// </summary>
        public static string CopyDetailsToolTip {
            get {
                return ResourceManager.GetString("CopyDetailsToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PngFiles.
        /// </summary>
        public static string PngFiles {
            get {
                return ResourceManager.GetString("PngFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AboutFlaUInspect.
        /// </summary>
        public static string AboutFlaUInspect {
            get {
                return ResourceManager.GetString("AboutFlaUInspect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RefreshToolTip.
        /// </summary>
        public static string RefreshToolTip {
            get {
                return ResourceManager.GetString("RefreshToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HoverModeToolTip.
        /// </summary>
        public static string HoverModeToolTip {
            get {
                return ResourceManager.GetString("HoverModeToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SelectModeToolTip.
        /// </summary>
        public static string SelectModeToolTip {
            get {
                return ResourceManager.GetString("SelectModeToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FocusTrackingToolTip.
        /// </summary>
        public static string FocusTrackingToolTip {
            get {
                return ResourceManager.GetString("FocusTrackingToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CaptureToolTip.
        /// </summary>
        public static string CaptureToolTip {
            get {
                return ResourceManager.GetString("CaptureToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GetStateToolTip.
        /// </summary>
        public static string GetStateToolTip {
            get {
                return ResourceManager.GetString("GetStateToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UIA2.
        /// </summary>
        public static string UIA2 {
            get {
                return ResourceManager.GetString("UIA2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UIA3.
        /// </summary>
        public static string UIA3 {
            get {
                return ResourceManager.GetString("UIA3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Identification.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PatternSupport.
        /// </summary>
        public static string PatternSupport {
            get {
                return ResourceManager.GetString("PatternSupport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        public static string Mixed {
            get {
                return ResourceManager.GetString("Mixed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NotSupported.
        /// </summary>
        public static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ErrorList.
        /// </summary>
        public static string ErrorList {
            get {
                return ResourceManager.GetString("ErrorList", resourceCulture);
            }
        }
    }
}
